project_name: project1
block_name: nbio_pcie_t
nick_name: run_01
libs_info: /home/chenanping/edp/source/libs/gen_libs/case/install/
workdir: $flow_path/../
pnr_innovus:
    upf_file: ""
    lowpower_design: "1"
    floorplan: ""
    r_power: "VDD"
    v_power: ""
    ground: "VSS"
    mmmc_file: $workdir/tune/pnr_innovus/viewDefinition.tcl
    netlist: /proj/flowdev/starC1/main/pd/echen/run08/datain/rrv64_core.synth.final.v
    cell_lefs: ""
    global_net_connect_file: $workdir/tune/pnr_innovus/global_net_connect.tcl 
    def: ""
    fp: ""



