syn_dc:
    default:
        cpu_num: 8
        memory: 10
        option: ""
        queue: "queue_syn"
        span: 1
    step1_dc:
        tool_opt: "dc_shell -f"
    config:
        projname: ""
        desname: ""
        workdir: "[pwd]"
        scrpath: ""
        dataintype: "RTL"
        rtl_pg_flag: "0"
        keep_redundant_regs: 1
        runmode: ""
        dcnxt: "0"
        ndm: 0
        mmmc: 0
        cgposcell: ""
        cgnegcell: ""
        clock_gating_max_flops: "32"
        clock_gating_stages_num: "2"
        auto_boundary: ""
        auto_ungroup: ""
        retime: ""
        spg: ""
        auto_path_group: 0
        min_route_layer: ""
        max_route_layer: ""
        critical_range: 0.2
        max_transition: ""
        max_capacitance: ""
        max_fanout:     ""
        set_load: ""
        driving_cell: ""
        dontouchinsts: ""
        dontouchnets: ""
        sizeonlyinsts: ""
        dontcginsts: ""
        dontmbinsts: ""
        nonscaninsts: ""
        keepboundmods: ""


    datain:
        filelist: ""
        premap_file: ""
        hdl_defines: "SYNTHESIS ASIC"
        sdc_file: "$syn_dc(config,workdir)/dbs/datain/$syn_dc(config,desname).sdc"
        upf_file: "$syn_dc(config,workdir)/dbs/datain/$syn_dc(config,desname).upf"
        extra_const_file: "$syn_dc(config,workdir)/config/usr_extra_const.tcl"
        saif_file: ""
        def_file: ""
        fp_file: ""
    techlib:
        process: "s4"
        stdlib_list: ""
        memlib_list: ""
        macrolib_list: ""
        dontuse_cell_list: "*/*D16* */*D20*"
        dontouch_cell_list: ""
        mwreflibs: ""
        techfile: ""
        mapfile: ""
        maxtluplus: ""
        mintluplus: ""
        tiecell: ""
    tool:
        version: [get_app_var sh_product_version]
        synlibpath: "/app/eda/synopsys/syn/$syn_dc(tool,version)/libraries/syn"
    flow:
        optstrategy: "timing"
        timingeffort: ""
        ungroupdw: "0"
        cpucores: "8"
        enable_scan: "0"
        incr_num: "1"
        compile_args: ""
        incr_stage: ""
        powerana: "0"
        debug_step: "link"
        restore_dbs: ""
        

        
