pv_calibre:
    fp_mode:
        - fp_ipmerge:
            in: data/fp.oas
            out: data/fp_merged.oas
            cmd: calibre_ipmerge.tcl
        - fp_dummy:
            - fp_feol:
                in: data/fp_merged.oas
                out: data/feol.oas
                cmd: fp_dummy.csh
            - fp_beol:
                in: data/fp_merged.oas
                out: data/beol.oas
                cmd: fp_dummy.csh
            - fp_dummy_merge:
                in: data/fp_merged.oas data/feol.oas data/beol.oas
                out: data/fp_merged_mfill.oas
                cmd: dummy_merge.csh
        - fp_pgshort:
            in: data/fp_merged_mfill.oas
            cmd: fp_pgshort.csh
        - fp_postshort:
            fp_drc:
                in: data/fp_merged_mfill.oas
                cmd: fp_drc.csh
            fp_perc:
                fp_p2p:
                    in: data/fp_merged.oas
                    cmd: perc/perc.csh
                fp_cd:
                    in: data/fp_merged.oas
                    cmd: perc.csh
                fp_topo:
                    in: data/fp_merged.oas
                    cmd: perc.csh
        - fp_db:
            in: fp_ipmerge fp_feol fp_beol fp_dummy_merge
        - fp_base:
            in: fp_drc
        - fp_esd:
            in: fp_p2p fp_cd fp_topo
        - fp_pv_all:
            in: fp_db fp_base fp_esd
    final_mode:
        - final_ipmerge:
            in: data/final.oas
            out: data/final_merged.oas
            cmd: final_ipmerge.csh
        - final_dummy:
            - final_feol:
                in: data/final_merged.oas
                out: data/final_merged.oas
                cmd: final_dummy.csh
            - final_beol:
                in: data/final_merged.oas
                out: data/final_beol.oas
                cmd: final_dummy.csh

    
