# Basic info setup

flow_name: JEDP_DEV
version: 1.0

# Project info setup
project_info:
    project1:
        TSMC: N5_H210
    project2:
        TSMC: N6_H280
    project3:
        SMIC: N28

# Secquence selection setup
pnr_innovus_run:
    - syn_genus
    - pnr_innovus
    - pv_calibre

pnr_fc_run:
    - syn_fc
    - pnr_fc
    - pv_calibre

